---
title: "Assignment 03"
author: "Roxane Peloux"
date: "2/9/2020"
output: html_document
editor_options: 
  chunk_output_type: inline
---

# Better Life Performances of OECD countries based on OECD's Better Life Index data 

Date

### By Roxane

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
BetterLifeIndex <- read_csv("BetterLifeIndex.csv")
library(tidyverse)
library(ggalt)
```

```{r}
names(BetterLifeIndex) 
str(BetterLifeIndex)
```
```{r}
unique(BetterLifeIndex$Indicator)
unique(BetterLifeIndex$Country)
unique(BetterLifeIndex$Unit)
```

```{r}
view(BetterLifeIndex)
```

```{r}

# Creating dataframe of only European OECD countries

BetterLifeIndex_European <- BetterLifeIndex %>%
  select(Country, Indicator, Inequality, Unit, Value) %>%
  filter(Country == "Austria" | Country == "Belgium" | Country == "Czech Republic" | Country == "Denmark" | Country == "Estonia" | Country == "Finland" | Country == "France" | Country == "Germany" | Country == "Greece" | Country == "Hungary" | Country == "Iceland" | Country == "Ireland" | Country == "Italy" | Country == "Latvia" | Country == "Luxembourg" | Country == "Netherlands" | Country == "Norway" | Country == "Poland" | Country == "Portugal" | Country == "Sloval Republic" | Country == "Slovenia" | Country == "Spain" | Country == "Sweden" | Country == "Switzerland" | Country == "United Kingdom")

# Creating dataframe of only European OECD countries for negative indicators 

BetterLifeIndex_European_bad <- BetterLifeIndex_European %>%
  select(Country, Indicator, Inequality, Unit, Value) %>%
  filter(Indicator == "Air pollution" | Indicator == "Dwellings without basic facilities" | Indicator == "Employees working very long hours" | Indicator == "Homicide rate" | Indicator == "Long-term unemployment rate")
  
# Creating a bar chart showing performance of OECD countries on negative indicators

  ggplot(BetterLifeIndex_European_bad, aes(x = reorder(Country, -Value), y = Value, fill = Indicator)) + geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Better life index performance on negative indicators \nfor European OECD countries", x = "Country", y = "Average score", caption = "The Average score for the different indicators is calculated \nin percentages, scores, ratio, US dollar, years, micrograms per cubic meter, or hours.", hjust = 1) 
    
```
```{r}

# Creating new dataframes with leisure/personal care and life satisfaction indicators for all countries to measure their correlation

Leisure <- BetterLifeIndex %>%
  filter(Indicator == "Time devoted to leisure and personal care" & Inequality == "Total") %>%
  select(Country, Value)

Life_Satisfaction <- BetterLifeIndex %>%
  filter(Indicator == "Life satisfaction" & Inequality == "Total") %>%
  select(Country, Value)

BetterLifeIndex_Leisure_Satisfaction <- inner_join(Leisure, Life_Satisfaction, by = "Country")

# Creating scatterplot of life satisfaction as a function of leisure and personal care by using the new dataframe created
 
ggplot(BetterLifeIndex_Leisure_Satisfaction[1:38,], aes(Value.x, Value.y)) + geom_point() +
  geom_point(data = BetterLifeIndex_Leisure_Satisfaction[39,], color = "blue") +
  labs(
    x = "Time devoted to leisure and personal care",
    y = "Life satisfaction",
    title = "Does more leisure make you happier?"
  )

# The blue dot represents OECD total (averaged)

```

```{r}
# Creating graph to measure gender inequality in feelings of safety

BetterLifeIndex_European %>%
  filter(Inequality %in% c("Men", "Women") & Indicator == "Feeling safe walking alone at night") %>%
  ggplot() +
  geom_line(aes(x = Value, y = Country), color = "grey") +
  geom_point(aes(x = Value, y = Country, color = Inequality), size = 1.5)+ 
  scale_color_manual(values = c("Women" = "Red", "Men" = "Blue")) + 
  labs(title = "Gender disparties in feelings of safety when walking alone \nat night in European OECD countries", x = "Ratio of respondents feeling safe walking alone at night \n(in percentages)", y = "Country") 

```








